apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dropx
  namespace: argocd
  annotations:
    # ArgoCD 앱 삭제 시에도 클러스터 리소스는 보존
    argocd.argoproj.io/sync-options: Delete=false
spec:
  project: default

  source:
    repoURL: http://192.168.10.100/root/ci.git
    targetRevision: main
    path: dropx-chart
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dropx

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground   # 삭제 순서 보장
      - RespectIgnoreDifferences=true       # ignoreDifferences 적용 보장

