apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dropx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://192.168.10.100/root/ci.git
    targetRevision: main
    path: dropx-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dropx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true